name: nix flake release
description: release all packages in a nix flake
author: trev

inputs:
  github_token:
    description: github token
    required: false
    default: ${{ github.token }}

runs:
  using: docker
  image: docker://ghcr.io/spotdemo4/nix-flake-release:0.4.0
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
