name: nix flake release
description: release all packages in a nix flake
author: trev

inputs:
  packages:
    description: nix packages to release
    required: false
    default: ""

  github_token:
    description: github token
    required: false
    default: ${{ github.token }}

  registry:
    description: container registry url
    required: false
    default: ghcr.io

  registry_username:
    description: container registry username
    required: false
    default: ${{ github.actor }}

  registry_password:
    description: container registry password
    required: false
    default: ${{ github.token }}

  bundle:
    description: whether to bundle nix derivations before archiving
    required: false
    default: ""

runs:
  using: docker
  image: docker://ghcr.io/spotdemo4/nix-flake-release:0.8.6
  env:
    ENV_ARGS: ${{ inputs.packages }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    REGISTRY: ${{ inputs.registry }}
    REGISTRY_USERNAME: ${{ inputs.registry_username }}
    REGISTRY_PASSWORD: ${{ inputs.registry_password }}
    BUNDLE: ${{ inputs.bundle }}
